obj-$(CONFIG_CGROUP_BPF) += cgroup.o
obj-$(CONFIG_BPF) += core.o
obj-$(CONFIG_BPF_SYSCALL) += percpu_freelist.o bpf_lru_list.o hashtab.o arraymap.o
obj-$(CONFIG_BPF_SYSCALL) += helpers.o
obj-$(CONFIG_BPF_SYSCALL) += syscall.o inode.o ringbuf.o stackmap.o lpm_trie.o devmap.o
obj-$(CONFIG_BPF_SYSCALL) += verifier.o
obj-$(CONFIG_BPF_SYSCALL) += btf.o map_in_map.o
